### ISSUE TITLE
Element not interactable

### ISSUE THREAD

**Issue by ZzzY1349** [kcajc/usvisa-ca#10]
The logs are below.

Session retry: 4
20:56:06 FOUND SLOT ON 2025-05-16!!!
Rescheduling failed:  Message: element not interactable
  (Session info: chrome=122.0.6261.58)
Stacktrace:
        GetHandleVerifier [0x00848C93+51395]
        (No symbol) [0x007B5EF1]
        (No symbol) [0x0066E004]
        (No symbol) [0x006A71C7]
        (No symbol) [0x0069E54E]
        (No symbol) [0x006C3E8C]
        (No symbol) [0x0069DF7E]
        (No symbol) [0x006C4124]
        (No symbol) [0x006DA570]
        (No symbol) [0x006C3C26]
        (No symbol) [0x0069C629]
        (No symbol) [0x0069D40D]
        GetHandleVerifier [0x00BC6453+3711107]
        GetHandleVerifier [0x00C0583A+3970154]
        GetHandleVerifier [0x00C00B28+3950424]
        GetHandleVerifier [0x008F9C99+776393]
        (No symbol) [0x007C16C4]
        (No symbol) [0x007BC5A8]
        (No symbol) [0x007BC759]
        (No symbol) [0x007ADD80]
        BaseThreadInitThunk [0x76A2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x776F7C5E+286]
        RtlGetAppContainerNamedObjectPath [0x776F7C2E+238]

**Comment by kcajc** [comment]
This step has been somewhat flaky because I can't really test it (i.e. really reschedule my test account's appointment). 

I suspect it's because of the short timeout. I'll add some more logging to better understand the problem for now.

**Comment by kcajc** [comment]
@ZzzY1349 I've added traceback for rescheduling errors, please let me know if this occurs again, thanks!

**Comment by kcajc** [comment]
#13 has more logs, closing this one for now.
