### ISSUE TITLE
Ability to also check other provinces.

### ISSUE THREAD

**Issue by dynacorp** [kcajc/usvisa-ca#11]
Currently, the program runs pretty smoothly, but can there be an enhancement to check other provinces and not just the default province for available dates? It might be a stretch but could come in handy.

**Comment by kcajc** [comment]
This is possible but I'm not sure what the app should do if it can find an earlier slot in another province. Making an appointment for another province with automation seems too risky.

**Comment by dynacorp** [comment]
Yh I think I quite agree with you, Thanks for the response. I will proceed to close this now.
