### ISSUE TITLE
Reschedule function not working

### ISSUE THREAD

**Issue by dynacorp** [kcajc/usvisa-ca#12]
Hi Team,

The script found an early date today and ran the reschedule function which was successful but my appointment date hasn't changed.
![Screenshot 2024-03-06 005225](https://github.com/kcajc/usvisa-ca/assets/20915993/37b07534-3ec6-4e0e-afd1-f5897067c4f2)

**Comment by kcajc** [comment]
I have observed this as a consequence of the slot being taken in the short timeframe between requesting availability and rescheduling. 

Unfortunately there are other automated script users so it's a very competitive process. This might be improved by rewriting the rescheduling steps with `requests` but I need a test account that I can actually reschedule.

**Comment by dynacorp** [comment]
that's quite unfortunate, I understand there is that problem with an account to test with. This might pose a problem as I believe it is difficult alone to find an available date.

**Comment by djluv** [comment]
Hello @kcajc - To let you know, this issue still persists. I found six availabilities yesterday and couldn't book a single one due to competitiveness. Any short term solutions that we can implement?

![image](https://github.com/kcajc/usvisa-ca/assets/82903195/a4d915fb-7e37-4acd-b893-25b38a275c3c)

**Comment by kcajc** [comment]
You may try shorter retry timeout. My experiment suggests that retrying too often will trigger some rate limit, but you can try tweaking the timeouts in settings.

**Comment by kcajc** [comment]
I think this is probably also fixed in #24, closing this one for now.
