### ISSUE TITLE
Element not interactable

### ISSUE THREAD

**Issue by dynacorp** [kcajc/usvisa-ca#13]
Got another date today but got an error, Element not interactable
![Screenshot 2024-03-06 212544](https://github.com/kcajc/usvisa-ca/assets/20915993/7ad35466-6a7c-4017-bf3a-fa53d4f69e78)
![Screenshot 2024-03-06 212525](https://github.com/kcajc/usvisa-ca/assets/20915993/89e1c49f-a7d1-47d5-b9f6-57dda7f0df63)

**Comment by kcajc** [comment]
I've added refresh before rescheduling in https://github.com/kcajc/usvisa-ca/commit/0900704c07a4abfeced11904cce8ed70a1b3db9a, please try the code on `dev` branch.

**Comment by dynacorp** [comment]
Just retried, same thing.

**Comment by djluv** [comment]
Can confirm, same thing when running in headless mode.

![image](https://github.com/kcajc/usvisa-ca/assets/82903195/47a382bf-2852-4440-b114-cc108b6aead0)

**Comment by kcajc** [comment]
I can't think of reason other than the timeout being too strict. I would need a test account for further investigation. Please let me know if you're willing to help.

**Comment by keremsafainan** [comment]
Boss I am having the same problem. Is there any update?

**Comment by Zizizzz** [comment]
Sir, Same problem here, any possible fix?

**Comment by Zizizzz** [comment]
![image](https://github.com/user-attachments/assets/eb730c30-6c3c-4ce7-9795-181c36a1e5ed)

**Comment by kcajc** [comment]
Looks like it's failing to click a button in the date selection UI. It could require just a trivial change in the matcher or a rewrite with `requests`.

I'm afraid I currently don't have the bandwidth nor an account with appointment to investigate. If you want to try fixing it yourself you could set a date cutoff with available slot (so that the program gets to the reschedule page) and investigate from there.

**Comment by zoe-L** [comment]
Changing line 19 of legacy_rescheduler.py to `"/html/body/div[4]/main/div[4]/div/div/form/fieldset/ol/fieldset/div/div[2]/div[3]/li[1]/input"` fixes the problem. 

Additionally, `AVAILABLE_DATE_REQUEST_SUFFIX` in settings.py is currently hardcoded to toronto consulate.

**Comment by kcajc** [comment]
@zoe-L Would you mind making a quick PR for this? Otherwise I will try to do the mentioned changes. Thanks!
