### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by CDP67** [kcajc/usvisa-ca#20]
Hi 

I am getting this error as below

/appointment/days/94.json?appointments%5Bexpedite%5D=false (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Error occured when requesting available dates

Could you please help with the fix ?

#SSLERROR

**Comment by kcajc** [comment]
I haven't seen any such reports. Have you tried running the script on different environments?

**Comment by kcajc** [comment]
Not reproducible, closing this for now.
