### ISSUE TITLE
Date is not being refreshed 

### ISSUE THREAD

**Issue by Diksha121-creator** [kcajc/usvisa-ca#22]
Hi , I tried ur script. It works fine. Have seen a scenario where 21/08/2026 was available but was not available later. But script was still showing that date is available atleast for next 2 hrs. 
![IMG_2923](https://github.com/user-attachments/assets/cd304622-4673-4585-b5d3-21944700d620)

**Comment by kcajc** [comment]
The showing available date part is written in requests and I would consider that the source of truth over the UI, which might display the available dates from a earlier fetch. Unless I’ve overlooked something, this doesn’t seem like a bug.

**Comment by kcajc** [comment]
That being said, I’ll keep an eye out for this during my (hopefully) upcoming maintenance for the repo.
