### ISSUE TITLE
continously reschedule for the best date available 

### ISSUE THREAD

**Issue by kaiwenShen** [kcajc/usvisa-ca#5]
rescheduling to an ideal time directly can be hard, rn I'm doing manual update of the MAX_WAIT_MONTH. I'm thinking of doing a continuous rescheduling that finds the best available month, reschedule, then update the best available month to current best-1, and continue the while loop. not sure how to do so, but it should be a good feature to have

**Comment by kcajc** [comment]
My only concern is their rule may not allow you to reschedule multiple times as mentioned in an email from the U.S. Consular Section in Toronto:

```
Do not try to reschedule your appointment more than one time since the option to see earlier capacity will only be given once. If you reschedule to an earlier appointment and try to reschedule again, you will not have the ability to see sooner/reserved appointment capacity and you will have to schedule a new appointment from the next regular appointment available which may be later than your current appointment.
```

**Comment by kcajc** [comment]
Due to the risk in rescheduling multiple times might ban the user from rescheduling, I think we probably don't need to implement this.  Or this can be done with a toggle in #8. Let's discuss in the #8, closing this for now.
