### ISSUE TITLE
New Appointment

### ISSUE THREAD

**Issue by ReLoadTR** [kcajc/usvisa-ca#6]
This works in (Türkiye) Turkey. But when he found a new appointment slot, he did not choose the time between 07:00 and 08:30. That's why I couldn't get a new appointment date.

_Sorry for the broken english, I used google translate._

**Comment by kcajc** [comment]
The default behavior is to select the latest time of the day and it at least had been working. Unfortunately at this point I don't have an account that can experiment with this. So if you want to fix it please look into these lines:

```
# Select time of the select_elem = driver.find_element(By.ID, 'appointments_consulate_appointment_time')
        select_elem.click()
        options = select_elem.find_elements(By.TAG_NAME, 'option')
        options[len(options)-1].click()
```

**Comment by ReLoadTR** [comment]
I will check it. Thank you so much
