### ISSUE TITLE
usvisa website refused to connect

### ISSUE THREAD

**Issue by Rita-coder** [kcajc/usvisa-ca#7]
Hi,

Thanks for uploading and sharing the code, I am also one uwaterloo student try to get an interview spot within1-2months. I runned your code and the website logged in unsucessfully for 5-6 times, and then the usvisa website refused to connect, do you have any clue? If you want to discuss via email, my university email start with j872wang, and I would like to pay for your help! Thank you!

**Comment by kcajc** [comment]
The website might implement some kind of rate limit. Please try tweaking the delay params in `settings.py` in #8.
